; Baijiu FID workstation installer.
; SourceDir is the materialized Tycho win64 product (baijiu-fid.exe + JustJ),
; not a PDE Product Export folder.
;
; Default layout after packaging\build-baijiu-win64.ps1 -Stage:
;   E:\OpenChrom\baijiu-fid-workstation\baijiu-fid.exe
;   E:\OpenChrom\baijiu-fid-workstation\baijiu-fid.ini   (-Xmx4096m)
;   E:\OpenChrom\baijiu-fid-workstation\BaijiuFID.ico   (company logo; -Stage copies packaging\BaijiuFID.ico)
;   E:\OpenChrom\baijiu-fid-workstation\jre\             (JustJ 25, installMode root)
;   E:\OpenChrom\baijiu-fid-workstation\plugins\
;   E:\OpenChrom\baijiu-fid-workstation\features\
;
; Desktop and Start Menu shortcuts set IconFilename to {app}\BaijiuFID.ico.
; Do not let them inherit baijiu-fid.exe: if the launcher brand step misses
; an icon, Windows still shows the Eclipse icon from the exe template.
; The .ico is taken from this script's directory ({#SourcePath}), so it ships
; even when SourceRoot is a raw Tycho folder. compiler: is the Inno Setup
; installation directory, not the script directory.
;
; Directory plug-ins are re-jarred by packaging\rejar-directory-plugins.ps1
; before this script runs, so class files are not loose paths over MAX_PATH.
; JustJ and the win32 launcher fragment stay directories.
;
; Install under {sd}\BaijiuFID (C:\BaijiuFID), not {autopf}\BaijiuFID.
; Program Files plus the Eclipse plugin tree exceeds MAX_PATH on plant PCs.
;
; ISCC itself still fails if SourceRoot is a long Maven target\products\...
; path. Override it (do not edit this file):
;   ISCC /DSourceRoot=E:\bjw packaging\BaijiuFID-Setup.iss
; build-baijiu-win64.ps1 -Stage -Destination E:\bjw copies the tree there.

#ifndef SourceRoot
#define SourceRoot "E:\OpenChrom\baijiu-fid-workstation"
#endif

#define MyAppName "白酒 FID 工作站"
#define MyAppVersion "1.6.32"
#define MyAppExeName "baijiu-fid.exe"

[Setup]
AppId={{7C4E9A21-6B18-4F0D-9E55-3A8C1D0B6F42}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=OpenChrom
; {sd}\BaijiuFID is C:\BaijiuFID when Windows is on C: (D:\BaijiuFID when
; Windows is on D:). UsePreviousAppDir=no so a failed install under
; Program Files is not reused.
DefaultDirName={sd}\BaijiuFID
UsePreviousAppDir=no
DefaultGroupName={#MyAppName}
OutputBaseFilename=BaijiuFID-Setup
OutputDir=..\..\installer
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
SourceDir={#SourceRoot}
UninstallDisplayIcon={app}\BaijiuFID.ico

[Files]
Source: "*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion; Excludes: "BaijiuFID.ico"
Source: "{#SourcePath}BaijiuFID.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\BaijiuFID.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\BaijiuFID.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "启动 {#MyAppName}"; Flags: nowait postinstall skipifsilent
